sudo: required
services:
  - docker
before_install:
  - docker build --no-cache -f Dockerfile.dev -t terrankartiktellus/fe_travis_ci:3.0 .
script:
  - docker run terrankartiktellus/fe_travis_ci:3.0 npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "ReactTravis"
  env: "ReactTravis-env"
  bucker_name: ""
  bucket_path: ""
  on:
    branch:master
  access_key_id: $aws_access_key
  secret_access_key:
    secure: "$aws_secret_key"