FROM node:alpine

WORKDIR /usr/app

COPY package.json .
RUN npm install

COPY . .
CMD [ "npm","start" ]

# docker build -t terrankartiktellus/fe_travis_ci:1.0 -f Dockerfile.dev .
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/usr/app terrankartiktellus/fe_travis_ci:1.0
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/usr/app -it terrankartiktellus/fe_travis_ci:1.0 npm run test
